// <auto-generated />
namespace ppedv.ElenasUwe.Data.EF.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class dt2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(dt2));
        
        string IMigrationMetadata.Id
        {
            get { return "201810120735270_dt2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
