// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace ppedv.ElenasUwe.Data.EF
{

    // Produkt
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.2.0")]
    public class ProduktConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<Produkt>
    {
        public ProduktConfiguration()
            : this("dbo")
        {
        }

        public ProduktConfiguration(string schema)
        {
            ToTable("Produkt", schema);
            HasKey(x => x.Id);

            Property(x => x.Id).HasColumnName(@"Id").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.Name).HasColumnName(@"Name").HasColumnType("nvarchar(max)").IsOptional();
            Property(x => x.Preis).HasColumnName(@"Preis").HasColumnType("decimal").IsRequired().HasPrecision(18,2);
            Property(x => x.IsDeleted).HasColumnName(@"IsDeleted").HasColumnType("bit").IsRequired();
            Property(x => x.Created).HasColumnName(@"Created").HasColumnType("datetime").IsRequired();
            Property(x => x.Modified).HasColumnName(@"Modified").HasColumnType("datetime2").IsRequired();
            HasMany(t => t.Zubereitungs).WithMany(t => t.Produkts).Map(m =>
            {
                m.ToTable("ZubereitungProdukt", "dbo");
                m.MapLeftKey("Produkt_Id");
                m.MapRightKey("Zubereitung_Id");
            });
        }
    }

}
// </auto-generated>
