// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace ppedv.ElenasUwe.Data.EF
{

    // Stoff
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.2.0")]
    public class Stoff
    {
        public int Id { get; set; } // Id (Primary key)
        public string Name { get; set; } // Name
        public int Aggregatzustand { get; set; } // Aggregatzustand
        public bool IsDeleted { get; set; } // IsDeleted
        public System.DateTime Created { get; set; } // Created
        public System.DateTime Modified { get; set; } // Modified

        // Reverse navigation

        /// <summary>
        /// Child Vorgangs (Many-to-Many) mapped by table [StoffVorgang]
        /// </summary>
        public virtual System.Collections.Generic.ICollection<Vorgang> Vorgangs { get; set; } // Many to many mapping

        public Stoff()
        {
            Vorgangs = new System.Collections.Generic.HashSet<Vorgang>();
        }
    }

}
// </auto-generated>
