// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace ppedv.ElenasUwe.Data.EF
{

    // Stoff
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.2.0")]
    public class StoffConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<Stoff>
    {
        public StoffConfiguration()
            : this("dbo")
        {
        }

        public StoffConfiguration(string schema)
        {
            ToTable("Stoff", schema);
            HasKey(x => x.Id);

            Property(x => x.Id).HasColumnName(@"Id").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.Name).HasColumnName(@"Name").HasColumnType("nvarchar(max)").IsOptional();
            Property(x => x.Aggregatzustand).HasColumnName(@"Aggregatzustand").HasColumnType("int").IsRequired();
            Property(x => x.IsDeleted).HasColumnName(@"IsDeleted").HasColumnType("bit").IsRequired();
            Property(x => x.Created).HasColumnName(@"Created").HasColumnType("datetime").IsRequired();
            Property(x => x.Modified).HasColumnName(@"Modified").HasColumnType("datetime2").IsRequired();
            HasMany(t => t.Vorgangs).WithMany(t => t.Stoffs).Map(m =>
            {
                m.ToTable("StoffVorgang", "dbo");
                m.MapLeftKey("Stoff_Id");
                m.MapRightKey("Vorgang_Id");
            });
        }
    }

}
// </auto-generated>
