// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace ppedv.ElenasUwe.Data.EF
{

    // Vorgang
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.2.0")]
    public class Vorgang
    {
        public int Id { get; set; } // Id (Primary key)
        public string Aktion { get; set; } // Aktion
        public System.TimeSpan Zeit { get; set; } // Zeit
        public bool IsDeleted { get; set; } // IsDeleted
        public System.DateTime Created { get; set; } // Created
        public System.DateTime Modified { get; set; } // Modified
        public int ZubereitungId { get; set; } // Zubereitung_Id

        // Reverse navigation

        /// <summary>
        /// Child Stoffs (Many-to-Many) mapped by table [StoffVorgang]
        /// </summary>
        public virtual System.Collections.Generic.ICollection<Stoff> Stoffs { get; set; } // Many to many mapping

        // Foreign keys

        /// <summary>
        /// Parent Zubereitung pointed by [Vorgang].([ZubereitungId]) (FK_dbo.Vorgang_dbo.Zubereitung_Zubereitung_Id)
        /// </summary>
        public virtual Zubereitung Zubereitung { get; set; } // FK_dbo.Vorgang_dbo.Zubereitung_Zubereitung_Id

        public Vorgang()
        {
            Stoffs = new System.Collections.Generic.HashSet<Stoff>();
        }
    }

}
// </auto-generated>
