// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace ppedv.ElenasUwe.Data.EF
{

    // Zubereitung
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.2.0")]
    public class Zubereitung
    {
        public int Id { get; set; } // Id (Primary key)
        public string Name { get; set; } // Name
        public bool IsDeleted { get; set; } // IsDeleted
        public System.DateTime Created { get; set; } // Created
        public System.DateTime Modified { get; set; } // Modified

        // Reverse navigation

        /// <summary>
        /// Child Produkts (Many-to-Many) mapped by table [ZubereitungProdukt]
        /// </summary>
        public virtual System.Collections.Generic.ICollection<Produkt> Produkts { get; set; } // Many to many mapping
        /// <summary>
        /// Child Vorgangs where [Vorgang].[Zubereitung_Id] point to this entity (FK_dbo.Vorgang_dbo.Zubereitung_Zubereitung_Id)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<Vorgang> Vorgangs { get; set; } // Vorgang.FK_dbo.Vorgang_dbo.Zubereitung_Zubereitung_Id

        public Zubereitung()
        {
            Vorgangs = new System.Collections.Generic.HashSet<Vorgang>();
            Produkts = new System.Collections.Generic.HashSet<Produkt>();
        }
    }

}
// </auto-generated>
